package cxf.pure.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-15T20:45:13.937+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "WetherServiceService",
                  wsdlLocation = "http://localhost:9001/wether?wsdl",
                  targetNamespace = "http://service.server.pure.cxf/")
public class WetherServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.server.pure.cxf/", "WetherServiceService");
    public final static QName WetherServicePort = new QName("http://service.server.pure.cxf/", "WetherServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9001/wether?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WetherServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9001/wether?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WetherServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WetherServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WetherServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WetherServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WetherServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WetherServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WetherService
     */
    @WebEndpoint(name = "WetherServicePort")
    public WetherService getWetherServicePort() {
        return super.getPort(WetherServicePort, WetherService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WetherService
     */
    @WebEndpoint(name = "WetherServicePort")
    public WetherService getWetherServicePort(WebServiceFeature... features) {
        return super.getPort(WetherServicePort, WetherService.class, features);
    }

}
